name: Code Quality Check

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DATABASE_URL: sqlite:///./test.db
      SECRET_KEY: test-secret-key-for-ci
      ADMIN_TOKEN: test-admin-token-for-ci

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with black
      run: |
        black --check --line-length=100 app/ tests/ run.py

    - name: Lint with ruff
      run: |
        ruff check --config=pyproject.toml app/ tests/ run.py

    - name: Run database migrations
      run: |
        alembic upgrade head

    - name: Test with pytest
      run: |
        pytest tests/ -v --cov=app --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
